codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project: # Overall project coverage
      default: # Default context
        target: auto
        threshold: 1%
        if_not_found: success
        if_ci_failed: error

    patch: # Coverage in the patch
      default:
        target: auto
        threshold: 1%
        if_not_found: success
        if_ci_failed: error

component_management:
  default_rules:
    statuses:
      - type: project
        target: auto
        branches:
          - "!main"
  individual_components:
    - component_id: module_util
      name: util
      paths:
        - typescript/src/util/**
    - component_id: module_components
      name: components
      paths:
        - typescript/src/components/**

comment:
  layout: "header, diff, components, files, footer"
  behavior: default
  require_changes: false
