codecov:
  notify:
    require_ci_to_pass: false

coverage:
  precision: 2
  round: down
  range: "60...100"

  status:
    project: # Overall project coverage
      default: # Default context
        target: 60
        threshold: 1%
        if_not_found: success
        if_ci_failed: error
        informational: true

    patch: # Coverage in the patch
      default:
        target: 90
        threshold: 1%
        if_not_found: success
        if_ci_failed: error
        informational: true

component_management:
  default_rules:
    statuses:
      - type: project
        target: auto
        branches:
          - "!main"
  individual_components:
    - component_id: module_util
      name: util
      paths:
        - typescript/src/util/**
    - component_id: module_components
      name: components
      paths:
        - typescript/src/components/**

comment:
  layout: "condensed_header, diff, flags, components, condensed_files, condensed_footer"
  behavior: default

github_checks:
  annotations: true

flag_management:
  individual_flags:
    - name: pytest-tests
      carryforward: true
      carryforward_mode: "labels"
      statuses:
        - type: "project"
        - type: "patch"

cli:
  plugins:
    pycoverage:
      report_type: "json"

flags:
  go-tests:
    carryforward: true
  jest-tests:
    carryforward: true
  cypress-tests:
    carryforward: true
  java-tests:
    carryforward: true
